# MONGO DB ATLAS (Database)
spring.data.mongodb.uri=mongodb+srv://munirabouzenni_db_user:moonstruck99@biblioteca.enmxsi0.mongodb.net/sistema_ingressos?retryWrites=true&w=majority&appName=Biblioteca
spring.data.mongodb.database=estetica_automotiva

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# Porta (server)
server.port=8080

# Log
logging.level.org.mongodb.driver=WARN
logging.level.com.estetica=INFO
